/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SelectedRouteImport } from './routes/selected'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesSlugRouteImport } from './routes/notes.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as ArtifactsSlugRouteImport } from './routes/artifacts.$slug'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectedRoute = SelectedRouteImport.update({
  id: '/selected',
  path: '/selected',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSlugRoute = NotesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NotesRoute,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionsRoute,
} as any)
const ArtifactsSlugRoute = ArtifactsSlugRouteImport.update({
  id: '/artifacts/$slug',
  path: '/artifacts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/notes': typeof NotesRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/selected': typeof SelectedRoute
  '/timeline': typeof TimelineRoute
  '/artifacts/$slug': typeof ArtifactsSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/notes/$slug': typeof NotesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/notes': typeof NotesRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/selected': typeof SelectedRoute
  '/timeline': typeof TimelineRoute
  '/artifacts/$slug': typeof ArtifactsSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/notes/$slug': typeof NotesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/notes': typeof NotesRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/selected': typeof SelectedRoute
  '/timeline': typeof TimelineRoute
  '/artifacts/$slug': typeof ArtifactsSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/notes/$slug': typeof NotesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/collections'
    | '/contact'
    | '/notes'
    | '/rss.xml'
    | '/selected'
    | '/timeline'
    | '/artifacts/$slug'
    | '/collections/$slug'
    | '/notes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/collections'
    | '/contact'
    | '/notes'
    | '/rss.xml'
    | '/selected'
    | '/timeline'
    | '/artifacts/$slug'
    | '/collections/$slug'
    | '/notes/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/collections'
    | '/contact'
    | '/notes'
    | '/rss.xml'
    | '/selected'
    | '/timeline'
    | '/artifacts/$slug'
    | '/collections/$slug'
    | '/notes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ContactRoute: typeof ContactRoute
  NotesRoute: typeof NotesRouteWithChildren
  RssDotxmlRoute: typeof RssDotxmlRoute
  SelectedRoute: typeof SelectedRoute
  TimelineRoute: typeof TimelineRoute
  ArtifactsSlugRoute: typeof ArtifactsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selected': {
      id: '/selected'
      path: '/selected'
      fullPath: '/selected'
      preLoaderRoute: typeof SelectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$slug': {
      id: '/notes/$slug'
      path: '/$slug'
      fullPath: '/notes/$slug'
      preLoaderRoute: typeof NotesSlugRouteImport
      parentRoute: typeof NotesRoute
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/artifacts/$slug': {
      id: '/artifacts/$slug'
      path: '/artifacts/$slug'
      fullPath: '/artifacts/$slug'
      preLoaderRoute: typeof ArtifactsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsSlugRoute: typeof CollectionsSlugRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsSlugRoute: CollectionsSlugRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface NotesRouteChildren {
  NotesSlugRoute: typeof NotesSlugRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesSlugRoute: NotesSlugRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ContactRoute: ContactRoute,
  NotesRoute: NotesRouteWithChildren,
  RssDotxmlRoute: RssDotxmlRoute,
  SelectedRoute: SelectedRoute,
  TimelineRoute: TimelineRoute,
  ArtifactsSlugRoute: ArtifactsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
