/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LensesRouteImport } from './routes/lenses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChefsDoeuvreRouteImport } from './routes/chefs-doeuvre'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesSlugRouteImport } from './routes/notes.$slug'
import { Route as LensesSlugRouteImport } from './routes/lenses.$slug'
import { Route as ArtifactsSlugRouteImport } from './routes/artifacts.$slug'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LensesRoute = LensesRouteImport.update({
  id: '/lenses',
  path: '/lenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefsDoeuvreRoute = ChefsDoeuvreRouteImport.update({
  id: '/chefs-doeuvre',
  path: '/chefs-doeuvre',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSlugRoute = NotesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NotesRoute,
} as any)
const LensesSlugRoute = LensesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LensesRoute,
} as any)
const ArtifactsSlugRoute = ArtifactsSlugRouteImport.update({
  id: '/artifacts/$slug',
  path: '/artifacts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chefs-doeuvre': typeof ChefsDoeuvreRoute
  '/contact': typeof ContactRoute
  '/lenses': typeof LensesRouteWithChildren
  '/notes': typeof NotesRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/artifacts/$slug': typeof ArtifactsSlugRoute
  '/lenses/$slug': typeof LensesSlugRoute
  '/notes/$slug': typeof NotesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chefs-doeuvre': typeof ChefsDoeuvreRoute
  '/contact': typeof ContactRoute
  '/lenses': typeof LensesRouteWithChildren
  '/notes': typeof NotesRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/artifacts/$slug': typeof ArtifactsSlugRoute
  '/lenses/$slug': typeof LensesSlugRoute
  '/notes/$slug': typeof NotesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chefs-doeuvre': typeof ChefsDoeuvreRoute
  '/contact': typeof ContactRoute
  '/lenses': typeof LensesRouteWithChildren
  '/notes': typeof NotesRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/artifacts/$slug': typeof ArtifactsSlugRoute
  '/lenses/$slug': typeof LensesSlugRoute
  '/notes/$slug': typeof NotesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chefs-doeuvre'
    | '/contact'
    | '/lenses'
    | '/notes'
    | '/rss.xml'
    | '/timeline'
    | '/artifacts/$slug'
    | '/lenses/$slug'
    | '/notes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chefs-doeuvre'
    | '/contact'
    | '/lenses'
    | '/notes'
    | '/rss.xml'
    | '/timeline'
    | '/artifacts/$slug'
    | '/lenses/$slug'
    | '/notes/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chefs-doeuvre'
    | '/contact'
    | '/lenses'
    | '/notes'
    | '/rss.xml'
    | '/timeline'
    | '/artifacts/$slug'
    | '/lenses/$slug'
    | '/notes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChefsDoeuvreRoute: typeof ChefsDoeuvreRoute
  ContactRoute: typeof ContactRoute
  LensesRoute: typeof LensesRouteWithChildren
  NotesRoute: typeof NotesRouteWithChildren
  RssDotxmlRoute: typeof RssDotxmlRoute
  TimelineRoute: typeof TimelineRoute
  ArtifactsSlugRoute: typeof ArtifactsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenses': {
      id: '/lenses'
      path: '/lenses'
      fullPath: '/lenses'
      preLoaderRoute: typeof LensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chefs-doeuvre': {
      id: '/chefs-doeuvre'
      path: '/chefs-doeuvre'
      fullPath: '/chefs-doeuvre'
      preLoaderRoute: typeof ChefsDoeuvreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$slug': {
      id: '/notes/$slug'
      path: '/$slug'
      fullPath: '/notes/$slug'
      preLoaderRoute: typeof NotesSlugRouteImport
      parentRoute: typeof NotesRoute
    }
    '/lenses/$slug': {
      id: '/lenses/$slug'
      path: '/$slug'
      fullPath: '/lenses/$slug'
      preLoaderRoute: typeof LensesSlugRouteImport
      parentRoute: typeof LensesRoute
    }
    '/artifacts/$slug': {
      id: '/artifacts/$slug'
      path: '/artifacts/$slug'
      fullPath: '/artifacts/$slug'
      preLoaderRoute: typeof ArtifactsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LensesRouteChildren {
  LensesSlugRoute: typeof LensesSlugRoute
}

const LensesRouteChildren: LensesRouteChildren = {
  LensesSlugRoute: LensesSlugRoute,
}

const LensesRouteWithChildren =
  LensesRoute._addFileChildren(LensesRouteChildren)

interface NotesRouteChildren {
  NotesSlugRoute: typeof NotesSlugRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesSlugRoute: NotesSlugRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChefsDoeuvreRoute: ChefsDoeuvreRoute,
  ContactRoute: ContactRoute,
  LensesRoute: LensesRouteWithChildren,
  NotesRoute: NotesRouteWithChildren,
  RssDotxmlRoute: RssDotxmlRoute,
  TimelineRoute: TimelineRoute,
  ArtifactsSlugRoute: ArtifactsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
