/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LensesRouteImport } from './routes/lenses'
import { Route as FrRouteImport } from './routes/fr'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ColophonRouteImport } from './routes/colophon'
import { Route as ChefsDoeuvreRouteImport } from './routes/chefs-doeuvre'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as LensesIndexRouteImport } from './routes/lenses.index'
import { Route as FrIndexRouteImport } from './routes/fr.index'
import { Route as NotesSlugRouteImport } from './routes/notes.$slug'
import { Route as LensesSlugRouteImport } from './routes/lenses.$slug'
import { Route as FrTimelineRouteImport } from './routes/fr.timeline'
import { Route as FrTermsRouteImport } from './routes/fr.terms'
import { Route as FrRssDotxmlRouteImport } from './routes/fr.rss[.]xml'
import { Route as FrPrivacyRouteImport } from './routes/fr.privacy'
import { Route as FrNotesRouteImport } from './routes/fr.notes'
import { Route as FrLensesRouteImport } from './routes/fr.lenses'
import { Route as FrContactRouteImport } from './routes/fr.contact'
import { Route as FrColophonRouteImport } from './routes/fr.colophon'
import { Route as FrChefsDoeuvreRouteImport } from './routes/fr.chefs-doeuvre'
import { Route as FrAboutRouteImport } from './routes/fr.about'
import { Route as EntriesSlugRouteImport } from './routes/entries.$slug'
import { Route as FrNotesIndexRouteImport } from './routes/fr.notes.index'
import { Route as FrLensesIndexRouteImport } from './routes/fr.lenses.index'
import { Route as FrNotesSlugRouteImport } from './routes/fr.notes.$slug'
import { Route as FrLensesSlugRouteImport } from './routes/fr.lenses.$slug'
import { Route as FrEntriesSlugRouteImport } from './routes/fr.entries.$slug'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LensesRoute = LensesRouteImport.update({
  id: '/lenses',
  path: '/lenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ColophonRoute = ColophonRouteImport.update({
  id: '/colophon',
  path: '/colophon',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefsDoeuvreRoute = ChefsDoeuvreRouteImport.update({
  id: '/chefs-doeuvre',
  path: '/chefs-doeuvre',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesRoute,
} as any)
const LensesIndexRoute = LensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LensesRoute,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrRoute,
} as any)
const NotesSlugRoute = NotesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NotesRoute,
} as any)
const LensesSlugRoute = LensesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LensesRoute,
} as any)
const FrTimelineRoute = FrTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => FrRoute,
} as any)
const FrTermsRoute = FrTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => FrRoute,
} as any)
const FrRssDotxmlRoute = FrRssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => FrRoute,
} as any)
const FrPrivacyRoute = FrPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => FrRoute,
} as any)
const FrNotesRoute = FrNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => FrRoute,
} as any)
const FrLensesRoute = FrLensesRouteImport.update({
  id: '/lenses',
  path: '/lenses',
  getParentRoute: () => FrRoute,
} as any)
const FrContactRoute = FrContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => FrRoute,
} as any)
const FrColophonRoute = FrColophonRouteImport.update({
  id: '/colophon',
  path: '/colophon',
  getParentRoute: () => FrRoute,
} as any)
const FrChefsDoeuvreRoute = FrChefsDoeuvreRouteImport.update({
  id: '/chefs-doeuvre',
  path: '/chefs-doeuvre',
  getParentRoute: () => FrRoute,
} as any)
const FrAboutRoute = FrAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => FrRoute,
} as any)
const EntriesSlugRoute = EntriesSlugRouteImport.update({
  id: '/entries/$slug',
  path: '/entries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FrNotesIndexRoute = FrNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrNotesRoute,
} as any)
const FrLensesIndexRoute = FrLensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrLensesRoute,
} as any)
const FrNotesSlugRoute = FrNotesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FrNotesRoute,
} as any)
const FrLensesSlugRoute = FrLensesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FrLensesRoute,
} as any)
const FrEntriesSlugRoute = FrEntriesSlugRouteImport.update({
  id: '/entries/$slug',
  path: '/entries/$slug',
  getParentRoute: () => FrRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chefs-doeuvre': typeof ChefsDoeuvreRoute
  '/colophon': typeof ColophonRoute
  '/contact': typeof ContactRoute
  '/fr': typeof FrRouteWithChildren
  '/lenses': typeof LensesRouteWithChildren
  '/notes': typeof NotesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/entries/$slug': typeof EntriesSlugRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/chefs-doeuvre': typeof FrChefsDoeuvreRoute
  '/fr/colophon': typeof FrColophonRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/lenses': typeof FrLensesRouteWithChildren
  '/fr/notes': typeof FrNotesRouteWithChildren
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/rss.xml': typeof FrRssDotxmlRoute
  '/fr/terms': typeof FrTermsRoute
  '/fr/timeline': typeof FrTimelineRoute
  '/lenses/$slug': typeof LensesSlugRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/fr/': typeof FrIndexRoute
  '/lenses/': typeof LensesIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/fr/entries/$slug': typeof FrEntriesSlugRoute
  '/fr/lenses/$slug': typeof FrLensesSlugRoute
  '/fr/notes/$slug': typeof FrNotesSlugRoute
  '/fr/lenses/': typeof FrLensesIndexRoute
  '/fr/notes/': typeof FrNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chefs-doeuvre': typeof ChefsDoeuvreRoute
  '/colophon': typeof ColophonRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/entries/$slug': typeof EntriesSlugRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/chefs-doeuvre': typeof FrChefsDoeuvreRoute
  '/fr/colophon': typeof FrColophonRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/rss.xml': typeof FrRssDotxmlRoute
  '/fr/terms': typeof FrTermsRoute
  '/fr/timeline': typeof FrTimelineRoute
  '/lenses/$slug': typeof LensesSlugRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/fr': typeof FrIndexRoute
  '/lenses': typeof LensesIndexRoute
  '/notes': typeof NotesIndexRoute
  '/fr/entries/$slug': typeof FrEntriesSlugRoute
  '/fr/lenses/$slug': typeof FrLensesSlugRoute
  '/fr/notes/$slug': typeof FrNotesSlugRoute
  '/fr/lenses': typeof FrLensesIndexRoute
  '/fr/notes': typeof FrNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chefs-doeuvre': typeof ChefsDoeuvreRoute
  '/colophon': typeof ColophonRoute
  '/contact': typeof ContactRoute
  '/fr': typeof FrRouteWithChildren
  '/lenses': typeof LensesRouteWithChildren
  '/notes': typeof NotesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/entries/$slug': typeof EntriesSlugRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/chefs-doeuvre': typeof FrChefsDoeuvreRoute
  '/fr/colophon': typeof FrColophonRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/lenses': typeof FrLensesRouteWithChildren
  '/fr/notes': typeof FrNotesRouteWithChildren
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/rss.xml': typeof FrRssDotxmlRoute
  '/fr/terms': typeof FrTermsRoute
  '/fr/timeline': typeof FrTimelineRoute
  '/lenses/$slug': typeof LensesSlugRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/fr/': typeof FrIndexRoute
  '/lenses/': typeof LensesIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/fr/entries/$slug': typeof FrEntriesSlugRoute
  '/fr/lenses/$slug': typeof FrLensesSlugRoute
  '/fr/notes/$slug': typeof FrNotesSlugRoute
  '/fr/lenses/': typeof FrLensesIndexRoute
  '/fr/notes/': typeof FrNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chefs-doeuvre'
    | '/colophon'
    | '/contact'
    | '/fr'
    | '/lenses'
    | '/notes'
    | '/privacy'
    | '/rss.xml'
    | '/terms'
    | '/timeline'
    | '/entries/$slug'
    | '/fr/about'
    | '/fr/chefs-doeuvre'
    | '/fr/colophon'
    | '/fr/contact'
    | '/fr/lenses'
    | '/fr/notes'
    | '/fr/privacy'
    | '/fr/rss.xml'
    | '/fr/terms'
    | '/fr/timeline'
    | '/lenses/$slug'
    | '/notes/$slug'
    | '/fr/'
    | '/lenses/'
    | '/notes/'
    | '/fr/entries/$slug'
    | '/fr/lenses/$slug'
    | '/fr/notes/$slug'
    | '/fr/lenses/'
    | '/fr/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chefs-doeuvre'
    | '/colophon'
    | '/contact'
    | '/privacy'
    | '/rss.xml'
    | '/terms'
    | '/timeline'
    | '/entries/$slug'
    | '/fr/about'
    | '/fr/chefs-doeuvre'
    | '/fr/colophon'
    | '/fr/contact'
    | '/fr/privacy'
    | '/fr/rss.xml'
    | '/fr/terms'
    | '/fr/timeline'
    | '/lenses/$slug'
    | '/notes/$slug'
    | '/fr'
    | '/lenses'
    | '/notes'
    | '/fr/entries/$slug'
    | '/fr/lenses/$slug'
    | '/fr/notes/$slug'
    | '/fr/lenses'
    | '/fr/notes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chefs-doeuvre'
    | '/colophon'
    | '/contact'
    | '/fr'
    | '/lenses'
    | '/notes'
    | '/privacy'
    | '/rss.xml'
    | '/terms'
    | '/timeline'
    | '/entries/$slug'
    | '/fr/about'
    | '/fr/chefs-doeuvre'
    | '/fr/colophon'
    | '/fr/contact'
    | '/fr/lenses'
    | '/fr/notes'
    | '/fr/privacy'
    | '/fr/rss.xml'
    | '/fr/terms'
    | '/fr/timeline'
    | '/lenses/$slug'
    | '/notes/$slug'
    | '/fr/'
    | '/lenses/'
    | '/notes/'
    | '/fr/entries/$slug'
    | '/fr/lenses/$slug'
    | '/fr/notes/$slug'
    | '/fr/lenses/'
    | '/fr/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChefsDoeuvreRoute: typeof ChefsDoeuvreRoute
  ColophonRoute: typeof ColophonRoute
  ContactRoute: typeof ContactRoute
  FrRoute: typeof FrRouteWithChildren
  LensesRoute: typeof LensesRouteWithChildren
  NotesRoute: typeof NotesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  TermsRoute: typeof TermsRoute
  TimelineRoute: typeof TimelineRoute
  EntriesSlugRoute: typeof EntriesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenses': {
      id: '/lenses'
      path: '/lenses'
      fullPath: '/lenses'
      preLoaderRoute: typeof LensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colophon': {
      id: '/colophon'
      path: '/colophon'
      fullPath: '/colophon'
      preLoaderRoute: typeof ColophonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chefs-doeuvre': {
      id: '/chefs-doeuvre'
      path: '/chefs-doeuvre'
      fullPath: '/chefs-doeuvre'
      preLoaderRoute: typeof ChefsDoeuvreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof NotesRoute
    }
    '/lenses/': {
      id: '/lenses/'
      path: '/'
      fullPath: '/lenses/'
      preLoaderRoute: typeof LensesIndexRouteImport
      parentRoute: typeof LensesRoute
    }
    '/fr/': {
      id: '/fr/'
      path: '/'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof FrRoute
    }
    '/notes/$slug': {
      id: '/notes/$slug'
      path: '/$slug'
      fullPath: '/notes/$slug'
      preLoaderRoute: typeof NotesSlugRouteImport
      parentRoute: typeof NotesRoute
    }
    '/lenses/$slug': {
      id: '/lenses/$slug'
      path: '/$slug'
      fullPath: '/lenses/$slug'
      preLoaderRoute: typeof LensesSlugRouteImport
      parentRoute: typeof LensesRoute
    }
    '/fr/timeline': {
      id: '/fr/timeline'
      path: '/timeline'
      fullPath: '/fr/timeline'
      preLoaderRoute: typeof FrTimelineRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/terms': {
      id: '/fr/terms'
      path: '/terms'
      fullPath: '/fr/terms'
      preLoaderRoute: typeof FrTermsRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/rss.xml': {
      id: '/fr/rss.xml'
      path: '/rss.xml'
      fullPath: '/fr/rss.xml'
      preLoaderRoute: typeof FrRssDotxmlRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/privacy': {
      id: '/fr/privacy'
      path: '/privacy'
      fullPath: '/fr/privacy'
      preLoaderRoute: typeof FrPrivacyRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/notes': {
      id: '/fr/notes'
      path: '/notes'
      fullPath: '/fr/notes'
      preLoaderRoute: typeof FrNotesRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/lenses': {
      id: '/fr/lenses'
      path: '/lenses'
      fullPath: '/fr/lenses'
      preLoaderRoute: typeof FrLensesRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/contact': {
      id: '/fr/contact'
      path: '/contact'
      fullPath: '/fr/contact'
      preLoaderRoute: typeof FrContactRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/colophon': {
      id: '/fr/colophon'
      path: '/colophon'
      fullPath: '/fr/colophon'
      preLoaderRoute: typeof FrColophonRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/chefs-doeuvre': {
      id: '/fr/chefs-doeuvre'
      path: '/chefs-doeuvre'
      fullPath: '/fr/chefs-doeuvre'
      preLoaderRoute: typeof FrChefsDoeuvreRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/about': {
      id: '/fr/about'
      path: '/about'
      fullPath: '/fr/about'
      preLoaderRoute: typeof FrAboutRouteImport
      parentRoute: typeof FrRoute
    }
    '/entries/$slug': {
      id: '/entries/$slug'
      path: '/entries/$slug'
      fullPath: '/entries/$slug'
      preLoaderRoute: typeof EntriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/notes/': {
      id: '/fr/notes/'
      path: '/'
      fullPath: '/fr/notes/'
      preLoaderRoute: typeof FrNotesIndexRouteImport
      parentRoute: typeof FrNotesRoute
    }
    '/fr/lenses/': {
      id: '/fr/lenses/'
      path: '/'
      fullPath: '/fr/lenses/'
      preLoaderRoute: typeof FrLensesIndexRouteImport
      parentRoute: typeof FrLensesRoute
    }
    '/fr/notes/$slug': {
      id: '/fr/notes/$slug'
      path: '/$slug'
      fullPath: '/fr/notes/$slug'
      preLoaderRoute: typeof FrNotesSlugRouteImport
      parentRoute: typeof FrNotesRoute
    }
    '/fr/lenses/$slug': {
      id: '/fr/lenses/$slug'
      path: '/$slug'
      fullPath: '/fr/lenses/$slug'
      preLoaderRoute: typeof FrLensesSlugRouteImport
      parentRoute: typeof FrLensesRoute
    }
    '/fr/entries/$slug': {
      id: '/fr/entries/$slug'
      path: '/entries/$slug'
      fullPath: '/fr/entries/$slug'
      preLoaderRoute: typeof FrEntriesSlugRouteImport
      parentRoute: typeof FrRoute
    }
  }
}

interface FrLensesRouteChildren {
  FrLensesSlugRoute: typeof FrLensesSlugRoute
  FrLensesIndexRoute: typeof FrLensesIndexRoute
}

const FrLensesRouteChildren: FrLensesRouteChildren = {
  FrLensesSlugRoute: FrLensesSlugRoute,
  FrLensesIndexRoute: FrLensesIndexRoute,
}

const FrLensesRouteWithChildren = FrLensesRoute._addFileChildren(
  FrLensesRouteChildren,
)

interface FrNotesRouteChildren {
  FrNotesSlugRoute: typeof FrNotesSlugRoute
  FrNotesIndexRoute: typeof FrNotesIndexRoute
}

const FrNotesRouteChildren: FrNotesRouteChildren = {
  FrNotesSlugRoute: FrNotesSlugRoute,
  FrNotesIndexRoute: FrNotesIndexRoute,
}

const FrNotesRouteWithChildren =
  FrNotesRoute._addFileChildren(FrNotesRouteChildren)

interface FrRouteChildren {
  FrAboutRoute: typeof FrAboutRoute
  FrChefsDoeuvreRoute: typeof FrChefsDoeuvreRoute
  FrColophonRoute: typeof FrColophonRoute
  FrContactRoute: typeof FrContactRoute
  FrLensesRoute: typeof FrLensesRouteWithChildren
  FrNotesRoute: typeof FrNotesRouteWithChildren
  FrPrivacyRoute: typeof FrPrivacyRoute
  FrRssDotxmlRoute: typeof FrRssDotxmlRoute
  FrTermsRoute: typeof FrTermsRoute
  FrTimelineRoute: typeof FrTimelineRoute
  FrIndexRoute: typeof FrIndexRoute
  FrEntriesSlugRoute: typeof FrEntriesSlugRoute
}

const FrRouteChildren: FrRouteChildren = {
  FrAboutRoute: FrAboutRoute,
  FrChefsDoeuvreRoute: FrChefsDoeuvreRoute,
  FrColophonRoute: FrColophonRoute,
  FrContactRoute: FrContactRoute,
  FrLensesRoute: FrLensesRouteWithChildren,
  FrNotesRoute: FrNotesRouteWithChildren,
  FrPrivacyRoute: FrPrivacyRoute,
  FrRssDotxmlRoute: FrRssDotxmlRoute,
  FrTermsRoute: FrTermsRoute,
  FrTimelineRoute: FrTimelineRoute,
  FrIndexRoute: FrIndexRoute,
  FrEntriesSlugRoute: FrEntriesSlugRoute,
}

const FrRouteWithChildren = FrRoute._addFileChildren(FrRouteChildren)

interface LensesRouteChildren {
  LensesSlugRoute: typeof LensesSlugRoute
  LensesIndexRoute: typeof LensesIndexRoute
}

const LensesRouteChildren: LensesRouteChildren = {
  LensesSlugRoute: LensesSlugRoute,
  LensesIndexRoute: LensesIndexRoute,
}

const LensesRouteWithChildren =
  LensesRoute._addFileChildren(LensesRouteChildren)

interface NotesRouteChildren {
  NotesSlugRoute: typeof NotesSlugRoute
  NotesIndexRoute: typeof NotesIndexRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesSlugRoute: NotesSlugRoute,
  NotesIndexRoute: NotesIndexRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChefsDoeuvreRoute: ChefsDoeuvreRoute,
  ColophonRoute: ColophonRoute,
  ContactRoute: ContactRoute,
  FrRoute: FrRouteWithChildren,
  LensesRoute: LensesRouteWithChildren,
  NotesRoute: NotesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  TermsRoute: TermsRoute,
  TimelineRoute: TimelineRoute,
  EntriesSlugRoute: EntriesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
